### ISSUE TITLE
Possible error with your sample code

### ISSUE THREAD

**Issue by equin0x80** [bzaar/DawgSharp#14]
I'm trying to get this to work in VS2008 so I've had to tweak the code a bit (to replace the => syntax with normal properties). Now it compiles; but when I try your simple Usage example from the GitHub project page, the Dawg.Save call fails:
"DawgSharp.Dawg<bool> does not contain a definition for Save..."

And indeed, the only Dawg.Save method is one with private accessibility and two parameters:
private void Save (Stream stream, Action <OldDawg<TPayload>, BinaryWriter> save)

Looks like I should use SaveTo instead (a public method) -- so does your sample code need fixing?

**Comment by bzaar** [comment]
Yes, SaveTo is the correct method to use. I've updated the README. Thanks for spotting that.

**Comment by bzaar** [comment]
Instead of trying to adopt the source code for C# 3.0, why not just use the [Nuget package](https://www.nuget.org/packages/DawgSharp/)?

**Comment by equin0x80** [comment]
I don't think VS2008 will support Nuget. I'll upgrade eventually. Anyway, I got it working. Thanks for your cool library, and for fixing the docs!
