### ISSUE TITLE
Unexpected behaviour of DawgBuilder.TryGetValue()

### ISSUE THREAD

**Issue by aligusnet** [bzaar/DawgSharp#22]
`DawgBuilder.TryGetValue()` might return true even the queried key has never been added. E.g.:

```cs
var builder = new DawgBuilder<string>();
builder.Insert("dates", "dates");
bool b = builder.TryGetValue("date", out var v);
Assert.Null(v);  // Okay
Assert.True(b);  // that's unexpected
```

I'd expect `b` to be `false` here because `"date"` was not added and no value were obtained by `TryGetValue()`

**Comment by bzaar** [comment]
That is indeed quite unexpected. The faulty implementation of TryGetValue is here:

https://github.com/bzaar/DawgSharp/blob/master/DawgSharp/DawgBuilder.cs#L65

Thanks for reporting this!
