### ISSUE TITLE
Error when loading bin file

### ISSUE THREAD

**Issue by Mukarillo** [bzaar/DawgSharp#24]
Hello,

I am receiving this error when trying to load a Dawg<bool> bin file
`unable to read beyond the end of the stream`

Here is how I am creating the dawg file:
```
string path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "/EN_words.txt";
var s = File.ReadAllLines(path);

var dawgBuilder = new DawgSharp.DawgBuilder<bool>();
foreach (var line in s)
{
   dawgBuilder.Insert(line, true);
}

var dawgpath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "/EN_dawg.bin";
var dawg = dawgBuilder.BuildDawg();
dawg.SaveTo(File.Create(dawgpath));
```

and here is how i am loading the dawg file

```
var fpath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "/EN_dawg.bin";
var file = File.Open(fpath, FileMode.Open);
dawgg = Dawg<bool>.Load(file);
```

The error occours in YaleDawg.cs at line 66.
![Screenshot 2020-02-27 at 19 49 30](https://user-images.githubusercontent.com/2946274/75476137-5b4f9800-599a-11ea-82e0-ba125b691282.png)

Thank you very much for the attention.

**Comment by Nogbit** [comment]
I'm having the same problems (same line and error).  

Though I did remove a bad line from my dictionary file and converted it all to lowercase.  Now I get to line 78 in your screenshot with the exact same error.

**Comment by Nogbit** [comment]
It's not a problem with the word file as I get the same errors with the file in this repos test project at `https://github.com/bzaar/DawgSharp/blob/master/DawgSharp.UnitTests/eneko-words.txt`.

**Comment by Mukarillo** [comment]
@Nogbit If I remember correctly I solved the issue by creating the file, and then saving, like this:

```
var file = File.Create(dawgpath);
dawg.SaveTo(file);
```

It has something to do with the position of the stream, but since the project's is licensed under GPLv3, I couldn't use to what I want... so I just gave up debugging.

Good luck tho :)

**Comment by bzaar** [comment]
Hi everyone,

Sorry a bit late to the party.

You need to close the file after you're done writing to it:

    using (var file = File.Create(dawgpath))
        dawg.SaveTo(file);

I will look into making the API more intuitive.

@Mukarillo, you can do anything you want with the library, once you get a commercial license. :)

**Comment by Nogbit** [comment]
@bzaar thanks, that worked!

**Comment by Nogbit** [comment]
@Mukarillo I sent you an email to licensing@morpher.co.uk asking about licensing cost, it may have went to your spam?

**Comment by Mukarillo** [comment]
@Nogbit I am not the developer of the tool, @bzaar is. Maybe he can help you with that 👍

**Comment by bzaar** [comment]
@Nogbit, I replied to your email.
