### ISSUE TITLE
How can i get a random word ?

### ISSUE THREAD

**Issue by kenofori** [bzaar/DawgSharp#25]
I want to pick a random word from dictionary, however there is no such method that can help with that. As you developed this amazing library so can you please guide how'd you approach such requirement?
Thanks

**Comment by bzaar** [comment]
There is no such method currently, but it can be done. Off the top of my head, I can think of two ways of implementing this:

1. Start at the root node and walk down the graph, choosing a child randomly. Unfortunately, this won't give you a uniform distribution. Longer words will appear less frequently.

2. To get a more uniform distribution across all DAWG items, you could point randomly into the [children array](https://github.com/bzaar/DawgSharp/blob/master/DawgSharp/YaleDawg.cs#L30) and then find the path from the root to this particular child.

As this is just my hobby project, I can't plan when I get around to implementing this.

**Comment by kenofori** [comment]
@bzaar i liked the children array approach, i can already see this array populated in debug view, so can you please give me a rough idea how can find the path if i choose a random child for example

{
charIndex: 18
index: 112350
}

**Comment by bzaar** [comment]
I've [committed](https://github.com/bzaar/DawgSharp/commit/09eafa2a1b65d253b5bfa25d776288781be0a6aa#diff-ee0ac1a7633d301f46d127bccfe0eb30R218) a first (suboptimal) version of ```GetRandomItem```. The word distribution may not be fully uniform but it shouldn't be too bad. Please see if this fits your requirements.

**Comment by kenofori** [comment]
Thanks @bzaar
Having something is better than having nothing.
