### ISSUE TITLE
Dawg.MatchSuffix feature? 

### ISSUE THREAD

**Issue by kenofori** [bzaar/DawgSharp#26]
Hi there,

This amazing library already has MatchPrefix which covers half of the cases. Can you please either provide MatchSuffix 
or advise how to implement this?

Thanks

**Comment by bzaar** [comment]
One way to get the MatchSuffix effect, would be to add the reversed keys and then use MatchPrefix():

> dawgBuilder.Insert ("key".Reverse(), true);

**Comment by bzaar** [comment]
Updated the docs: https://github.com/bzaar/DawgSharp/blob/master/README.md#matchprefix

**Comment by kenofori** [comment]
@bzaar does it mean i create a secondary dawg which contains reverse words only to check for suffixes?

**Comment by bzaar** [comment]
If you need to check for both prefixes and suffixes, then yes. If it's only suffixes, then you may manage with just one dawg. Just remember to flip the words before showing them to the user!

**Comment by kenofori** [comment]
Thanks
