### ISSUE TITLE
Dawg.MatchSuffix with max Count

### ISSUE THREAD

**Issue by kenofori** [bzaar/DawgSharp#27]
Hi there,

Currently MathSuffx returns all the words which maynot be ideal in some situation so please provide a maxCount optional argument which for example if i say 10 then if then i get only maximum 10 words.

Thanks

**Comment by bzaar** [comment]
```
using System.Linq;

dawg.MatchPrefix("pre").Take(10);
```

**Comment by kenofori** [comment]
Problem with this is that it still create a super slow down response when im trying to fill a scrabble grid with all the combination, im getting over 30k combination with one alphabet

**Comment by bzaar** [comment]
Have you tried it out? I don't think ```MatchPrefix("pre").Take(10)``` will be slow.

**Comment by bzaar** [comment]
Please provide more context if this is still an issue.
