### ISSUE TITLE
Consider MIT or LGPL please?

### ISSUE THREAD

**Issue by BrianMcBrayer** [bzaar/DawgSharp#7]
Hello,

I'm thinking about recommending this to be used in an upcoming project, but I can't use GPL code. Could you release this as possibly LGPL? I'd be happy to maybe help contribute to the project if I find problems with the code (if this DAWG implementation gets selected), but the licensing thing is a showstopper.

Great library, by the way! Thanks for considering!

**Comment by bzaar** [comment]
Hi Brian,

Thanks for having a look at my library. Indeed, GPL is a tricky beast. However, it does not stop me from issuing other licenses, including commerial ones.

As a fellow (ardent) software developer, you must appreciate the amount of effort that was put into this library: the idea behind the DAWG is quite simple; it's all about implementation details, the numerous decisions and trade-offs, some quite non-trivial. One of the trickiest things for me (and the one that brought the most performance gain) was using integer arrays to represent the graph. Endless nights of profiling also did the library much good.

If someone were to develop such a library from scratch aiming for similar metrics, they would be looking at weeks if not months of development time. Hence the argument: it's cheaper to buy and spread the cost of development across multiple customers. 

If you are interested in getting a commercial license, please drop me a line at sergey@morpher.co.uk and we'll take it from there.

Thanks,
Sergey

P.S. Great blog by the way. The only thing it's missing is a Subscribe button (at least in the mobile version).

**Comment by BrianMcBrayer** [comment]
Hi Sergey,

Thank you for your thoughtful response. I appreciate that your selection of license was well considered; many developers use the GPL without knowing all of its implications (which are not bad, just not usable for my purposes at the moment), but this is not the case with you. I am scouting options and really like this DAWG implementation, though I do not know whether I will be allowed to use it or not. Let's keep in touch.

I didn't know anyone read my blog, so I had never considered a Subscribe button. I'll have to consider that. :)

Thanks,
Brian
