### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by RalfSmith** [bzaar/DawgSharp#9]
I am trying this simple piece of code, for benchmarking purposes, but I get an OutOfMemoryException when reaching around 350K elements inserted. 

DawgBuilder<bool> dawgBuilder = new DawgBuilder<bool>();
for (int i = 0; i < 10000000; i++)
{
      dawgBuilder.Insert(Guid.NewGuid().ToString(), true);
}

**Comment by bzaar** [comment]
Have you tried running this code in a 64 bit process?

**Comment by bzaar** [comment]
Also, this class is built to store natural language strings efficiently.
Using it with Guids will not give you the benefits this class was designed
to provide.

**Comment by RalfSmith** [comment]
I will compile it as x64, and let you know. I read in the documentation the remark about the benefits of storing words, but I wanted (needed) to create a testing environment for different data structures as neutral as possible. 

Thank you very much for your extremely fast response!

**Comment by bzaar** [comment]
You're welcome. But keep in mind that whatever benchmarks you do on Guids
may not reflect the timings on natural language words. I would highly
recommend testing on data that you want to use in production.

Also, can you post your benchmark results here?

**Comment by bzaar** [comment]
Hi @RalfSmith,

How did the testing go? Did it work in x64?
